#!/usr/bin/env bash
# print out the subdomain info

get_info() {
	ip=$(dig "$1" | grep -A1 'ANSWER SECTION:' | awk '{ print $5 }' | tr -d '\n')
	type=$(dig "$1" | grep -A1 'ANSWER SECTION:' | awk '{ print $4 }' | tr -d '\n')
	echo "The subdomain $2 is a $type record and points to $ip"
}

if [ "$2" ]; then
	get_info "$2.$1" "$2"
else
    get_info "www.$1" "www"
    get_info "lb-01.$1" "lb-01"
    get_info "web-01.$1" "web-01"
    get_info "web-02.$1" "web-02"
fi
