#!/usr/bin/env bash
# configure nginx
sudo apt-get update
sudo apt-get -y install nginx
sed -i "23i\add_header X-Served-By $HOSTNAME;" /etc/nginx/sites-available/default
sed -i "23i\add_header X-Served-By $HOSTNAME;" /etc/nginx/sites-available/default
sudo service nginx restart
