#!/usr/bin/env bash
# prints bad luck on 4, good luck on 8, otherwise Holberton School

i="1"

while [ $i -le 10 ]
do
if [ $i -eq 4 ]
then
	echo "bad luck"
elif [ $i -eq 8 ]
then
	echo "good luck"
else
	echo "Holberton School"
fi
i=$((i+1))
done
