#!/usr/bin/env bash
# prints info about file

if [ -e holbertonschool ]; then
	echo "holbertonschool file exists"
else
	echo "holbertonschool file does not exist"
	if [ -s holbertonschool ]; then
		echo "holbertonschool file is not empty"
	else
		echo "holbertonschool file is empty"
	fi
	if [ -f holbertonschool ]; then
		echo "holbertonschool is a regular file"
	fi
fi
