#!/usr/bin/env bash
# transfer files to server

file_path="$1"
ip="$2"
username="$3"
key_path="$4"
if [ $# -eq 4 ]
then
	scp -i $key_path $file_path $username@$ip:~/
else
	echo Usage: 0-transfer_file PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY
fi
