#!/usr/bin/env bash
# configure nginx to run on nginx user
sudo pkill apache2
sudo chown nginx:nginx /etc/nginx/nginx.conf
sudo chmod 644 /etc/nginx/nginx.conf
sudo sed -i 's/80/8080/' /etc/nginx/sites_available/default
sudo -u nginx nginx
